apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-utils
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: net-utils
  template:
    metadata:
      labels:
        app: net-utils
    spec:
      containers:
      - name: net-utils
        image: barm0leykin/net-utils
        args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 100; done']
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
